### ISSUE TITLE
How to use XamlViewer with wpf classes?

### ISSUE THREAD

**Issue by jcbritobr** [huangjia2107/XamlViewer#6]
How to use XamlViewer with wpf classes? The dotnetcore window and other components are not recognized in the editor.

![image](https://user-images.githubusercontent.com/6579862/99434973-3d421300-28ee-11eb-9fa0-7a0bd6b038b0.png)

**Comment by huangjia2107** [comment]
The usage shown in the picture is not supported, each tab is independent, can you tell me the reason for this?

**Comment by jcbritobr** [comment]
> 
> 
> The usage shown in the picture is not supported, each tab is independent, can you tell me the reason for this?

I was trying to develop wpf applications using it. Is there a way to use it for wpf app development?

**Comment by huangjia2107** [comment]
Sorry about that, XamlViewer is just a xaml editor for designing style or layout.

**Comment by jcbritobr** [comment]
Ok, I'll close this issue. Thank you by the feedback. 👍
