### ISSUE TITLE
XamlViewer opens in new window instead of tab, when an existing windows is open.

### ISSUE THREAD

**Issue by poroburu** [huangjia2107/XamlViewer#8]
Occurs when I try to open using Explorer context menu "Open with... >" using the netcoreapp3.1 v1.3 release.

There does not seem to be a reason for multiple instances to be open with the tabbed viewer. The new window contains both tabs, but the old window remains.

**Comment by huangjia2107** [comment]
The latest master code has supported this feature, and I will release a new version. ^-^
